---
namespace: smallstep
name: sigstore
version: 0.0.1
readme: README.md
authors:
  - Joe Doss @jdoss
  - Smallstep Engineering
description: Verify artifacts with Sigstore
license:
  - Apache-2.0
license_file: 'LICENSE'
tags:
  - sigstore
  - smallstep
  - pki
dependencies: {}
repository: https://github.com/smallstep/ansible-collection-sigstore
documentation: https://github.com/smallstep/ansible-collection-sigstore/README.md
homepage: https://smallstep.com
issues: https://github.com/smallstep/ansible-collection-sigstore/issues
build_ignore: []
