name: Run Ansible Integration Tests
on: [push, pull_request]
jobs:
  integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/smallstep/sigstore

    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
        with:
          path: ansible_collections/smallstep/sigstore

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Ansible
        run: pip install ansible

      - name: Run the integration tests
        run: ansible-test integration
